### ISSUE TITLE
API response not giving consistent values

### ISSUE THREAD

**Issue by rmccullagh** [binlist/data#141]
We're seeing `null` being returned in the `prepaid` property. It's been determined that `true` or `false` are not the only values of that property. I believe this is a bug.

**Comment by tjconcept** [comment]
Hi Ryan,

Thanks for reaching out.

We've recently rolled out a newer version of the API (3) which fixes a lot of issues. If you haven't switched already, I encourage you to give it a shot.

Regarding `null` being returned in some places - that's actually not a bug. It happens if you provide too little information to narrow down to a single issuing range (sometimes it is actually impossible from the card number alone), or the information is simply not available.
I will add a note about the possibility f `null` to the website.

Feel free to reopen this issue, if you have further questions.
